### ISSUE TITLE
2.0.0 changelog?

### ISSUE THREAD

**Issue by dcousens** [scottcorgan/httpify#4]

**Comment by joseph-onsip** [comment]
It was mostly a bunch of dependency updates prompted by #3. You can see the changes here: https://github.com/scottcorgan/httpify/compare/1.0.0...2.0.0

**Comment by scottcorgan** [comment]
Ya, I need to update the deps to the latest anyways. There's another project called [nets](https://github.com/maxogden/nets) as well, that kind of is the same thing.

**Comment by scottcorgan** [comment]
Closing as @joseph-onsip clarified
