### ISSUE TITLE
How do i add authorization Header

### ISSUE THREAD

**Issue by sajumani** [scottcorgan/httpify#7]
Hi

I want to add Authorization header to all service call...

**Comment by josephfrazier** [comment]
[You can use the `request`/`xhr` syntax to specify options](https://github.com/scottcorgan/httpify/blob/b19bc34501f9dc55e76e6b59859ffd23bed0451d/README.md#usage). Here's an example:

``` javascript
var httpify = require('httpify')

var options = {
  url: 'https://httpbin.org/headers',
  headers: {
    'Authorization': 'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='
  }
}

httpify(options).then(function (response) {
  console.log(JSON.stringify(response, null, 2))
})
```

**Comment by scottcorgan** [comment]
Exactly. Thanks @josephfrazier.
